### PR TITLE
Add doc checking to helper.pl

### PR DESCRIPTION
**Pull request by karel-m**
As suggested in another PR I have added a check whether all macros and functions from `tommath.h` are documented in `doc/bn.tex`.

Current status:
```
$ ./helper.pl -d
[missing_doc_for_function] mp_2expt
[missing_doc_for_function] mp_abs
[missing_doc_for_function] mp_addmod
[missing_doc_for_function] mp_clamp
[missing_doc_for_function] mp_cnt_lsb
[missing_doc_for_function] mp_complement
[missing_doc_for_function] mp_copy
[missing_doc_for_function] mp_count_bits
[missing_doc_for_function] mp_div_3
[missing_doc_for_function] mp_dr_is_modulus
[missing_doc_for_function] mp_exch
[missing_doc_for_function] mp_export
[missing_doc_for_function] mp_fread
[missing_doc_for_function] mp_fwrite
[missing_doc_for_function] mp_get_double
[missing_doc_for_function] mp_import
[missing_doc_for_function] mp_is_square
[missing_doc_for_function] mp_mod_2d
[missing_doc_for_function] mp_mulmod
[missing_doc_for_function] mp_n_root_ex
[missing_doc_for_function] mp_rand
[missing_doc_for_function] mp_read_signed_bin
[missing_doc_for_function] mp_reduce_2k_l
[missing_doc_for_function] mp_reduce_2k_setup_l
[missing_doc_for_function] mp_reduce_is_2k
[missing_doc_for_function] mp_reduce_is_2k_l
[missing_doc_for_function] mp_set_double
[missing_doc_for_function] mp_signed_bin_size
[missing_doc_for_function] mp_sqrmod
[missing_doc_for_function] mp_sqrt
[missing_doc_for_function] mp_submod
[missing_doc_for_function] mp_tc_and
[missing_doc_for_function] mp_tc_div_2d
[missing_doc_for_function] mp_tc_or
[missing_doc_for_function] mp_tc_xor
[missing_doc_for_function] mp_to_signed_bin
[missing_doc_for_function] mp_to_signed_bin_n
[missing_doc_for_function] mp_to_unsigned_bin_n
[missing_doc_for_function] mp_toradix_n
[missing_doc_for_function] mp_zero
[missing_doc_for_macro] mp_iseven
[missing_doc_for_macro] mp_isneg
[missing_doc_for_macro] mp_isodd
[missing_doc_for_macro] mp_iszero
[missing_doc_for_macro] mp_mag_size
[missing_doc_for_macro] mp_raw_size
[missing_doc_for_macro] mp_read_mag
[missing_doc_for_macro] mp_read_raw
[missing_doc_for_macro] mp_tobinary
[missing_doc_for_macro] mp_todecimal
[missing_doc_for_macro] mp_tohex
[missing_doc_for_macro] mp_tomag
[missing_doc_for_macro] mp_tooctal
[missing_doc_for_macro] mp_toraw
check_doc:       FAIL 54
```

### CODE REVIEW

**Comment by sjaeckel** [comment]
damn, that's more work than I expected :-D

**Comment by czurnieden** [comment]
> damn, that's more work than I expected :-D

No, it isn't, @sjaeckel  ;-)

Thought I did everything correct, but I didn't. Obviously. As expected ;-)
So if someone want's to plug it out of #136 : you're welcome.

Not all the findings were implemented, some of them are more or less internal (private) functions, I think. Add them nevertheless?

**Comment by karel-m** [comment]
After rebasing on current develop
```
$ ./helper.pl -d
[missing_doc_for_function] mp_complement
[missing_doc_for_function] mp_dr_is_modulus
[missing_doc_for_function] mp_get_double
[missing_doc_for_function] mp_mod_2d
[missing_doc_for_function] mp_mulmod
[missing_doc_for_function] mp_n_root_ex
[missing_doc_for_function] mp_reduce_2k_l
[missing_doc_for_function] mp_reduce_2k_setup_l
[missing_doc_for_function] mp_reduce_is_2k
[missing_doc_for_function] mp_reduce_is_2k_l
[missing_doc_for_function] mp_set_double
[missing_doc_for_function] mp_sqrmod
[missing_doc_for_function] mp_submod
[missing_doc_for_function] mp_to_signed_bin_n
check_doc:       FAIL 14
```

**Comment by sjaeckel** [comment]
That's why I'd leave this PR until after the release ;-)

**Comment by minad** [comment]
@karel-m Is this ready to merge?

**Comment by karel-m** [comment]
After rebasing there are still these issues:
```
$ ./helper.pl -d
[missing_doc_for_function] mp_complement
[missing_doc_for_function] mp_dr_is_modulus
[missing_doc_for_function] mp_get_double
[missing_doc_for_function] mp_mulmod
[missing_doc_for_function] mp_n_root_ex
[missing_doc_for_function] mp_reduce_2k_l
[missing_doc_for_function] mp_reduce_2k_setup_l
[missing_doc_for_function] mp_reduce_is_2k
[missing_doc_for_function] mp_reduce_is_2k_l
[missing_doc_for_function] mp_set_double
[missing_doc_for_function] mp_sqrmod
[missing_doc_for_function] mp_submod
[missing_doc_for_function] mp_to_signed_bin_n
check_doc:       FAIL 13
```

**Comment by sjaeckel** [comment]
> After rebasing there are still these issues:

I'll open another PR which adds a travis target to always run this check where those errors must then be fixed

**Pull request merged**
