### PR TITLE
Fix packagecloud repo- and packagename

### PR DESCRIPTION
**Pull request by sjaeckel**

### CODE REVIEW

**Comment by sjaeckel** [comment]
I'll leave this open for comments on #557

**Comment by sjaeckel** [comment]
The versioning should be done compliant to https://linux.die.net/man/5/deb-version

**Comment by czurnieden** [comment]
That could be helpful for MoarVM (I think it's @MasterDuke17 who "represesents" them here?).

>  https://linux.die.net/man/5/deb-version

For those who have trouble parsing a natural language (e.g.: me ;-) ) it is formally [(ABNF)](https://www.rfc-editor.org/rfc/rfc5234)

```abnf
DECDIGIT     = %x30-39                            ; 0-9
ALNUM        = DECDIGIT / (%x41–5A / %x61–7A)     ; A-Za-z0-9
EXTRA        = %x2e / %x2b / %x7e                 ; '.' period, '+' plus, '~' tilde
COLON        = %x3a                               ; ':' colon
MINUS        = %x2d                               ; '-' minus

EPOCH        = 1*DECDIGIT COLON
DEBREVISION  = MINUS 1*(ALNUM / EXTRA)

UPSTRVER     = DECDIGIT / ALNUM / EXTRA           ; Upstream version number (original version number)

UPVERSION    = 1*DECDIGIT *UPSTRVER                   ; No extras
UPVERSIONEP  = 1*DECDIGIT *(UPSTRVER / COLON)         ; Epoch exists
UPVERSIONDEB = 1*DECDIGIT *(UPSTRVER / MINUS)         ; Debian revision number exists
UPVERSIONALL = 1*DECDIGIT *(UPSTRVER / COLON / MINUS) ; Both, an epoch and a Debian revision number exists

DEBVERSION  =  (EPOCH UPVERSIONALL DEBREVISION)
            =/ (EPOCH UPVERSIONEP             )
            =/ (      UPVERSIONDEB DEBREVISION)
            =/ (      UPVERSION               )
```

(Please correct me if I  made an error)

**Comment by sjaeckel** [comment]
> For those who have trouble parsing a natural language (e.g.: me ;-) ) it is formally [(ABNF)](https://www.rfc-editor.org/rfc/rfc5234)

thx, that's exactly what I needed :D 

I've renamed the packages now to `libtommath-git` resp. `libtommath-git-dev` if they originate from a non-tagged commit. This also allows us to publish an "official" `libtommath` resp. `libtommath-dev` package once we made a new release.

**Pull request merged**
