### PR TITLE
No grow in mp_set_int* (2)

### PR DESCRIPTION
**Pull request by minad**
Based on #221, I tried to simplify some things. No padding to MP_PREC anymore. Ping @nijtmans

### CODE REVIEW

**Comment by sjaeckel** [comment]
can you please also fix the travis.yml so it doesn't start two builds if the branch starts with travis/ or is that intended?

**Comment by minad** [comment]
It was intended. I wanted to test both commits.

**Comment by minad** [comment]
But I am not sure if travis starts every run twice for PR branches called travis/. I just had this branch as travis/ first for CI to run. It is probably a bad idea to have PR branches called travis.

**Comment by sjaeckel** [comment]
> It is probably a bad idea to have PR branches called travis.

yep, that's what I meant

but I like the idea of having a way to test separate commits!

**Comment by minad** [comment]
> but I like the idea of having a way to test separate commits!

Yes, therefore I called it originally like this.

**Pull request closed without merging**
