### PR TITLE
explicit logical XOR

### PR DESCRIPTION
**Pull request by fperrad**
for coverity CID 332946, see #163

### CODE REVIEW

**Comment by sjaeckel** [comment]
@fperrad can you please rebase, then we can merge this

**Comment by minad** [comment]
@sjaeckel Is it not possible to merge this directly given that there are no conflicts?

**Comment by sjaeckel** [comment]
possible - yes

desirable - depends on what you want and I prefer to have linear history with exactly one type of merge-commit and that's "PR back into develop" and similar important merges.

Sure I could also do the rebase myself and force-push to the fork of @fperrad, but I always feel bad when I push to the repo of someone else... :) 

Why do I insist on linear history? Because I think it improves readability and traceability (e.g. bisect becomes easier)

Also the rebase has the side-effect that it triggers a re-test of this PR as travis is still shown as green, whereas that's a lie. Yeah, Github nowadays tells me something about 'This branch is out-of-date.. yadda yadda' and asks to merge develop back into this branch, but that'd be against readability again.

**Comment by minad** [comment]
Hmm they should offer a rebase and merge button

**Comment by sjaeckel** [comment]
> Hmm they should offer a rebase and merge button

yeah, as soon as this one AI startup has this final real AI solution... probably then there are also going to be 'Fix this issue' and 'Implement this feature' buttons when opening an issue/feature request ;-)

**Comment by minad** [comment]
Trivial cases like this one handles the git ai pretty well...

**Comment by fperrad** [comment]
@sjaeckel rebased

**Pull request merged**
