### PR TITLE
deprecate mp_prime_random_ex in favor of mp_prime_rand

### PR DESCRIPTION
**Pull request by minad**
@czurnieden Since we have a good default random source now, we can provide a simpler api for random prime generation, such that the primes are safe for cryptographical use.

### CODE REVIEW

**Comment by czurnieden** [comment]
> Since we have a good default random source now,[&hellip;]

Indeed.

Changes of the API need to be well documented. I don't see `doc/bn.tex` included in the list of changed files.
Hey, why the long face? You wrote it, you document it! &gt;;->

**Comment by minad** [comment]
Sure I will. This is not done. I just made this PR since it is faster to tell you by code then by words. So you would generally agree with this PR? @sjaeckel?

**Comment by czurnieden** [comment]
> So you would generally agree with this PR

Yes.

**Comment by minad** [comment]
I guess I have to add some docs then. Long face now.

**Comment by minad** [comment]
docs updated

**Pull request merged**
