### PR TITLE
some lintings

### PR DESCRIPTION
**Pull request by fperrad**
this set of patches solves problems found with a lint tool (with some [MISRA C  2012](https://en.wikipedia.org/wiki/MISRA_C) rules).

I try to have a commit per kind of problem.

### CODE REVIEW

**Comment by czurnieden** [comment]
The commit 1459be0581048effc6b71b1370d0c1002dea8638 "fix parenthese when assignment in a condition" is indeed a bug not just an inelegancy. I would recommend merging at least that.

**Comment by sjaeckel** [comment]
Looks nice
Seriously 42a0e6113 ? I think we should either leave it like it was, or really fix it and check the return values, but I won't merge that commit :-)

**Comment by fperrad** [comment]
I purposely put this commit https://github.com/libtom/libtommath/commit/42a0e6113527a27d437226eae562621e25f98198 at the end of the serie, so it's easy to exclude it.

**Comment by TazeTSchnitzel** [comment]
Oh wow, I didn't even know a cast to `(void)` was valid C.

**Comment by sjaeckel** [comment]
I already forgot that under some misrable circumstances you have to write such ugly code :-)

But TBH I like that you brought this up, because it's basically an error that we don't check these return values, so we must go on and fix them instead of casting the problems away.

**Pull request closed without merging**
