### PR TITLE
fix appveyor.yml

### PR DESCRIPTION
**Pull request by sjaeckel**
It looks like appveyor doesn't understand its own exported format...

As it is now and works it sets the projects settings and if I click on "Export YAML" it has the same format as orginally committed by @minad ...

ping @FeodorFitsner @IlyaFinkelshteyn

### CODE REVIEW

**Comment by minad** [comment]
What is the issue? Line endings? Did you change something here?

**Comment by sjaeckel** [comment]
It looks like the multi-line `build_script` variable doesn't work

```
build_script:
- cmd: >-
...
```

**Comment by IlyaFinkelshteyn** [comment]
Please check in the bottom of [this part of doc](https://www.appveyor.com/docs/build-configuration/#script-blocks-in-build-configuration), it says:

> spaces between lines created by **Export YAML** menu are mandatory

Sorry for confusion.

**Comment by sjaeckel** [comment]
> Please check in the bottom of [this part of doc](https://www.appveyor.com/docs/build-configuration/#script-blocks-in-build-configuration), it says:
> 
> > spaces between lines created by **Export YAML** menu are mandatory
> 
> Sorry for confusion.

There are no spaces between lines, _but_ it looks like the indentation was modified...

**Pull request merged**
