### PR TITLE
Move disabling of warning C4003 from makefile.msvc to tommath_private.h

### PR DESCRIPTION
**Pull request by nijtmans**

### CODE REVIEW

**Comment by minad** [comment]
Maybe add a comment to the warning magic number? Otherwise :+1:

**Comment by minad** [comment]
@sjaeckel also merge to develop or will you rebase develop later on 1.2?

**Comment by sjaeckel** [comment]
I will merge the final tag back to develop as soon as the release is done

**Comment by sjaeckel** [comment]
FYI I would want to continue merging the finished 2.0 PR's but I'm waiting for @lvc regarding https://github.com/libtom/libtommath/issues/233#issuecomment-542677789
or should I just continue as it seems that all is fine and we fixed the remaining errors of the ABI?

**Pull request merged**
