### PR TITLE
more lintings

### PR DESCRIPTION
**Pull request by fperrad**
this set of patches contains:
- 3 patches against the new file `bn_mp_sqrtmod_prime.c`
- 4 patches against the whole code base

### CODE REVIEW

**Comment by sjaeckel** [comment]
Cool thanks.
Can you please change the (void) casts to proper error handling?

**Comment by TazeTSchnitzel** [comment]
Is bracketing everything a good idea? BODMAS is something people are no doubt familiar with, the interpretation of `a + b * c` is unambiguous.

**Comment by fperrad** [comment]
Done, the 3rd commit of the PR is updated.


2015-11-13 12:28 GMT+01:00 Steffen Jaeckel <notifications@github.com>:

**Comment by fperrad** [comment]
I've removed the patch concerning `for (;;)` from the series.

**Pull request closed without merging**
