### PR TITLE
Add Swift Package Manager support

### PR DESCRIPTION
**Pull request by cntrump**

### CODE REVIEW

**Comment by sjaeckel** [comment]
I'm not sure if this belongs here, shouldn't this be tracked in some swift package repository?

**Comment by cntrump** [comment]
> I'm not sure if this belongs here, shouldn't this be tracked in some swift package repository?

If this repo add SPM support, others can directly add a reference to this repository.

**Review by royjit — APPROVED** [review]

**Comment by royjit** [comment]
We would like to have this feature as well. I was able to successfully test this change in a Swift library that I am working

**Comment by sjaeckel** [comment]
OK, could you maybe add a short example to the `demo` folder with a little bit of documentation on how to use it?

Do you also plan to add the same to ltc?

**Comment by cntrump** [comment]
> Do you also plan to add the same to ltc?
Yes, I will commit a SwiftPM support PR for libtomcrypt after this PR merged.

**Comment by cntrump** [comment]
> Do you also plan to add the same to ltc?

Done.

**Comment by sjaeckel** [comment]
Wow, that's more than I expected :)

Huge :+1:

**Comment by royjit** [comment]
Do you have plans to tag this as a release soon? I see that the last tagged release was on Oct 2019.

**Pull request merged**
