### PR TITLE
Barrett todecimal

### PR DESCRIPTION
**Pull request by MasterDuke17**
https://github.com/libtom/libtommath/pull/330, but rebased onto feature-detection2 so `mp_todecimal` can be converted into a function that uses `MP_HAS` to selectively use the new `s_mp_todecimal_fast`.

### CODE REVIEW

**Comment by MasterDuke17** [comment]
@minad @czurnieden @sjaeckel how does this look? I'm in the process of adding tests, but I'm not sure about documentation. How much is needed and where does it go?

**Comment by minad** [comment]
Looks good! The CI should be green and we need tests. You can test against mp_toradix for random numbers.

**Comment by MasterDuke17** [comment]
@minad The two problems in travis are the same, but I'm not exactly sure how to fix them.
```
bn_s_mp_todecimal_fast.c:16:28: warning: implicitly declaring library function 'snprintf' with type 'int (char *, unsigned long, const char *, ...)' [-Wimplicit-function-declaration]

      int new_pos = left ? snprintf(*result, 4, "%u", mp_get_i32(number)) : snprintf(*result, 4, "%03u",

                           ^

bn_s_mp_todecimal_fast.c:16:28: note: include the header <stdio.h> or explicitly provide a declaration for 'snprintf'
```
However, stdio.h is already included. Some googling suggests other people have seem similar problems and it's some weird thing about different versions of header files. Do you have any suggestions?

**Comment by minad** [comment]
Snprintf should not be used.

**Comment by sjaeckel** [comment]
closed again in favor of #330

**Pull request closed without merging**
