### PR TITLE
remove footers & headers

### PR DESCRIPTION
**Pull request by minad**

### CODE REVIEW

**Comment by sjaeckel** [comment]
Why?

**Comment by minad** [comment]
See #210. Why are they needed? Is there a reason to keep them?

**Comment by sjaeckel** [comment]
It happened already multiple times that some bug report came in where someone didn't know the exact version of the file, but I have to admit that this was already some time ago that this happened last.

TBH I mostly forgot about the footer as it's just there and why would I touch it or even look at it? you're saying it's even "distracting you".. seriously? why? I would even say I like its existence because it clearly shows the end of the file and I don't have to worry about missing or excessive empty lines at the end of the file ;-)

...and it's filled-in when creating the tarball.

**Comment by minad** [comment]
This is a matter of taste, it feels like a relict and looks antiquated. My perception is just that I prefer dense information without ornaments. And emacs usually shows me the end of the file ;)

Since @czurnieden did something concerning the footer in #210, I thought why even bother and just applied some regexes quickly.

At least I understand now when these vars are filled in. I still consider these footers a misfeature since I would rather have the files in the tarball matching the files in git. But this is my preference.

Another thing are those file headers which I consider unnecessary and I always have to scroll over them. I would prefer something a bit shorter, there is no need to mention in every file that libtommath was designed after MPI etc etc.

But no need to discuss such trivialities really, if you don't like it and want to keep things as is, you can just close this one.

**Comment by sjaeckel** [comment]
> it feels like a relict

it definitely is there for historical reasons, as is the header...

**Comment by minad** [comment]
Concerning the header duplication - for example many projects having long GPL headers moved on and just use SPDX identifiers (e.g. Linux). Generally I have nothing against systematic file headers, if they contain only a short line saying to which lib the file belongs and then maybe some longer comment about the purpose of the file. In tommath the "purpose comment" comes later just before the function.

**Comment by sjaeckel** [comment]
Alright -- all or nothing -- get rid of the header and footer.

@karel-m what do you think? keep them or remove them? We'd do the same for ltc before the next release.

**Comment by sjaeckel** [comment]
@czurnieden can you please wait with rebasing your remaining PR's until this is resolved? :)

then you can also squash the remaining "formatting" commits of the branches please

**Comment by minad** [comment]
@sjaeckel Now they are completely gone. I think is it good like that since all the metadata is available in the documentation and the README.

**Comment by minad** [comment]
Alternatively a very short header might be appropriate.

~~~ c
/* LibTomMath, multiple-precision integer library -- Tom St Denis */
/* SPDX-License-Identifier: Unlicense */
~~~

**Comment by sjaeckel** [comment]
I like the short header

**Comment by minad** [comment]
@sjaeckel done

**Comment by sjaeckel** [comment]
can you please also rebase ;-) the build hasn't even started yet so we have to wait anyways

**Comment by minad** [comment]
rebased :unamused:

**Comment by karel-m** [comment]
Steffen Jaeckel wrote:

> @karel-m <https://github.com/karel-m> what do you think? keep them or
> remove them? We'd do the same for ltc before the next release
>

I am fine with removing them.

>

**Comment by czurnieden** [comment]
> then you can also squash the remaining "formatting" commits of the branches please

Yes, I know, I should have done it before pushing but: it was late, my HDD is 5 years old and pushing is faster than firing up my backup mechanism. And, to be honest, it was slowly starting to gnaw on my nerves, wanted it it out of my sight ;-)

> can you please wait with rebasing your remaining PR's until this is resolved? :)

I was waiting for the XCALLOC thing needed for the `mp_factors*`&hellip;uh, you already merged it, thanks! But after that I'm stuck without the sieve. 
I could go on with the fast division algorithms, but they don't really work without `mp_balance` (and TC-4,5).

OK, twiddlling thumbs now.

**Comment by sjaeckel** [comment]
> rebased :unamused:

I'll rebase for you the next time...

**Comment by sjaeckel** [comment]
> Yes, I know, I should have done it before pushing but

no worries, the PR's need review and will probably need some changes

I just wanted to make sure it happens :) 



> I was waiting for the XCALLOC thing needed for the `mp_factors*`…uh, you already merged it, thanks! But after that I'm stuck without the sieve.
> I could go on with the fast division algorithms, but they don't really work without `mp_balance` (and TC-4,5).

in which order do those remaining PR's make most sense to review (and merge) for you?

**Pull request merged**
