### PR TITLE
Better interoperability between MSVC and mingw-w64, 3

### PR DESCRIPTION
**Pull request by nijtmans**
Another try, sucessor of the -2 branch. I don't know how to integrate generate_def.sh with helper.pl.

The .def-file doesn't include deprecated symbols, that's on purpose: I don't really care about those ;-)

### CODE REVIEW

**Comment by nijtmans** [comment]
B.T.W: the current  makefile.mingw in develop is wrong: it contains too many lines with duplicate .o-files. Fixed in this branch!

**Comment by minad** [comment]
> ...we have to fix the dependency system...

@czurnieden and I talked about improving the configuration system before. Maybe I find time to work on this at some point and propose a PR.

**Comment by nijtmans** [comment]
> I generally approve but I think we have to fix the dependency system to handle bn_conversion.c and bn_deprecated.c. Furthermore the def generation should be part of helper.pl later.

Agreed!   Actually, I don't care about bn_deprecated.c, but the bn_conversion.c symbols - indeed - must be handled separately. I don't know how to do that better, without actually deriving the symbols from a built library. Yes, it should be part of helper.pl later!

**Comment by minad** [comment]
> I don't know how to do that better, without actually deriving the symbols from a built library.

Either we split bn_deprecated/bn_conversion again per function or we improve the regex "parser" in helper.pl which generates tommath_class etc. The def file should also be generated from that data then.

**Comment by nijtmans** [comment]
I think this one is ready to be merged to develop. Further improvements/cleanups in generating the .def-file can be done in a separate PR.

**Comment by minad** [comment]
Agree, there is already something going on in #301

**Comment by minad** [comment]
@sjaeckel I think this is ready too?

**Comment by nijtmans** [comment]
@sjaeckel    ping ???

**Pull request merged**
