### PR TITLE
workaround for the MoarVM problem with MP_GEN_RAND et al.

### PR DESCRIPTION
**Pull request by czurnieden**
This is a questionable but (hopefully) working "solution" for the current MoarVM problem.
It is questionable because it supresses the errors of a cryptographic function.

### CODE REVIEW

**Comment by sjaeckel** [comment]
woah, yeah, that could be a solution, but I guess we should wait for the MoarVM guys to assess the possible solutions before we merge this :)

**Comment by czurnieden** [comment]
Oh, Clang doesn't like `__attribute__((unused))`?
But you are right, of course. And also: once you start to implement workarounds for other peoples software&hellip;you know that spiel, don't you? \*sigh\*

**Comment by czurnieden** [comment]
@sjaeckel Because it was a simple change I prepared a patch for MoarV but sending that needs this or a similar one to be implemented in the new version (would be rc3?) Kind of catch-22, sorry.

Oh: here it is https://github.com/MoarVM/MoarVM/compare/master...czurnieden:master

**Comment by sjaeckel** [comment]
> I took the liberty to implement your idea

awesome, thanks!

> the new version (would be rc3?)

yep, that'd require an rc3! :) I will cherry-pick the merge-commit to the release-branch then

but still: the @MoarVM team hasn't replied yet, so we'll have to wait

**Comment by czurnieden** [comment]
I gave MoarVM a hint for how to change their code to implement your `mp_rand_digit` by way of a pull request here https://github.com/MoarVM/MoarVM/pull/1034

**Comment by timo** [comment]
We're going to have a release in about 3 days, but I don't see a problem with just applying the pull request immediately (though I have changed the name of "our own" mp_double_get function to have MVM_ instead of s_ as a prefix, so that needs a tiny change); I read somewhere that we're "ignoring a warning from a cryptographic function", but I can't find that comment any more, and I didn't quite understand what that meant?

Is there a good reason not to merge the PR almost-as-is and perhaps even ship the newest release with a release candidate of libtommath included in our own repository?

**Comment by czurnieden** [comment]
> though I have changed the name of "our own" mp_double_get function to have MVM_ instead of s_ as a prefix, so that needs a tiny change

OK, did it. Conflicts? Oh, you already did it, sorry, my bad.

> I read somewhere that we're "ignoring a warning from a cryptographic function",

Couldn't find it either, at least not quickly, but you *do* ignore the returns of the LTM-functions I saw (didn't go with a fine comb through your code). Those returns contain, with only one or two exceptions, the error codes, so I guess that might have been the reason.

> Is there a good reason not to merge the PR almost-as-is and perhaps even ship the newest release with a release candidate of libtommath included in our own repository?

Uhm&hellip;could it be that you posted that in the wrong group or is this post a copy of a (private?) discussion?

**Comment by sjaeckel** [comment]
@timo I'm mostly waiting for MoarVM, so if this PR is fine for you I'd merge it, make an RC3 and as soon as @dod38fr gave the okay I'll finish the release (so you can package the final release of ltm)

**Comment by timo** [comment]
> > Is there a good reason not to merge the PR almost-as-is and perhaps even ship the newest release with a release candidate of libtommath included in our own repository?
> 
> Uhm…could it be that you posted that in the wrong group or is this post a copy of a (private?) discussion?

No, this was meant to be publicly read by you all. Though maybe I should have made clearer that the PR that should be merged as-is is the one for moarvm, not the one I'm commenting on right here.

> you _do_ ignore the returns of the LTM-functions I saw

right, that's actually true. I could go through the code and check return values in all the places we use mp functions, that'd probably be a good idea just in general.

**Comment by timo** [comment]
I just manually merged the random number generator related changes from @czurnieden's pull request and pushed it up to master

**Pull request merged**
