### PR TITLE
Fixed bug in mp_prime_isprime

### PR DESCRIPTION
**Pull request by czurnieden**
Random witness to Miller-Rabin cannot be equal to input to MIller-Rabin

### CODE REVIEW

**Comment by minad** [comment]
thank you for looking into it so quickly :+1:

**Comment by czurnieden** [comment]
The alternative is based on my first idea. It is much faster but it wastes 1 bit of entropy. On the other hand: it is a very rare event for larger numbers.

**Comment by czurnieden** [comment]
@sjaeckel this is a security fix. Is it grave enough to go into the current version (assuming the patch (ffec6f1) is correct and accepted by the rest of the crew, of course!) instead of `develop`?

**Comment by sjaeckel** [comment]
> @sjaeckel this is a security fix. Is it grave enough to go into the current version (assuming the patch ([ffec6f1](https://github.com/libtom/libtommath/commit/ffec6f1447b532c5d83a6055aa4337fe01c58d89)) is correct and accepted by the rest of the crew, of course!) instead of `develop`?

we can go through the PR's merged since the last release and make a bugfix-release, I see more than this patch in there!

I've created a new milestone [v1.1.1](https://github.com/libtom/libtommath/milestone/4) and will later today go through the PR's since v1.1.0 and assign them to this milestone, feel free to do so as well!

**Comment by sjaeckel** [comment]
> I've created a new milestone [v1.1.1](https://github.com/libtom/libtommath/milestone/4) and will later today go through the PR's since v1.1.0 and assign them to this milestone, feel free to do so as well!

I will then cherry-pick all those PR's to the to-be-created v1.1.1 branch

**Pull request merged**
