### PR TITLE
Add 'const' keyword in various places. Adopted from Tcl

### PR DESCRIPTION
**Pull request by sjaeckel**
Follow-up of #86

### CODE REVIEW

**Comment by nijtmans** [comment]
I think this branch is ready to be merged to develop.

**Comment by sjaeckel** [comment]
I think so too, I'll merge after @fperrad checked it

**Comment by nijtmans** [comment]
@fperrad ping?

**Comment by fperrad** [comment]
my linter find few other places, see https://github.com/fperrad/libtommath/commit/d293ab66041ac368342d204681658db5f4393e09

**Comment by sjaeckel** [comment]
Can you push this to the branch of this PR please

**Comment by sjaeckel** [comment]
@nijtmans fine like that for you as well!?

**Comment by nijtmans** [comment]
Sure, fully fine with me!  +1

**Pull request merged**
