### PR TITLE
mp_sqrtmod_prime

### PR DESCRIPTION
**Pull request by karel-m**
related to issue https://github.com/libtom/libtommath/issues/33

### CODE REVIEW

**Comment by sjaeckel** [comment]
```
gcc -I./ -Wall -W -Wshadow -Wsign-compare -O3 -funroll-loops -fomit-frame-pointer   -c -o bn_mp_sqrtmod_prime.o bn_mp_sqrtmod_prime.c
bn_mp_sqrtmod_prime.c: In function ‘mp_sqrtmod_prime’:
bn_mp_sqrtmod_prime.c:39:3: warning: passing argument 3 of ‘mp_mod_d’ from incompatible pointer type [enabled by default]
   if ((res = mp_mod_d(prime, 4, &i)) != MP_OKAY)                goto cleanup;
   ^
In file included from bn_mp_sqrtmod_prime.c:1:0:
./tommath.h:395:5: note: expected ‘mp_digit *’ but argument is of type ‘long unsigned int *’
 int mp_mod_d(mp_int *a, mp_digit b, mp_digit *c);
     ^
```

**Comment by sjaeckel** [comment]
c.f. https://github.com/libtom/libtommath/tree/feature/mp_sqrtmod_prime

**Comment by karel-m** [comment]
To get rid of the above mentioned compiler warning try:
```diff
-  unsigned long i;
+  mp_digit i;
```

**Comment by sjaeckel** [comment]
Thanks!
Can you do the following please?

1. fetch libtom/libtommath
1. checkout your branch
1. `git reset --hard <your name of the libtom mirror>/feature/mp_sqrtmod_prime`
1. force-push that branch to your fork and continue working on that

Btw. I can convert your few paragraphs into TeX if you send me what I should convert.

**Comment by tomstdenis** [comment]
I've rebased this privately and merged it into develop.

**Pull request closed without merging**
