### PR TITLE
[WIP] add windows builds to travis

### PR DESCRIPTION
**Pull request by sjaeckel**

### CODE REVIEW

**Comment by sjaeckel** [comment]
I give up
who wants to try?

**Comment by minad** [comment]
I tried for a minute. But I found neither documentation nor a working example anywhere. An alternative could be appveyor. 

Maybe someone who knows windows could try? @karel-m or @nijtmans? I haven't really used it for ~15 years.

**Comment by sjaeckel** [comment]
> Maybe someone who knows windows could try? @karel-m or @nijtmans?

that'd be a great idea

> I tried for a minute. But I found neither documentation nor a working example anywhere. An alternative could be appveyor.

I asked the travis support, they gave me a link to this config [1] which somehow succeeded in setting it up but after a short retry I'm giving up again...

[1] https://github.com/floorman/temper/blob/master/.travis.yml

**Comment by minad** [comment]
I tried quickly using appveyor and at least I managed to start "nmake -f makefile.msvc all" but then I got a parse error (seperator : missing or sth)?! Can some windows user please try this?

**Comment by minad** [comment]
will be superseded by #297

**Pull request closed without merging**
