### PR TITLE
deprecate mp_prime_is_divisible and ltm_prime_tab

### PR DESCRIPTION
**Pull request by minad**
* it is an implementation detail used for prime testing
* there is upcoming work by @czurnieden regarding a generalised prime sieve
* furthermore remove jacobi test (replaced by kronecker)

### CODE REVIEW

**Comment by minad** [comment]
@czurnieden I know you argued before that we will probably keep this function just as a quick early test. But I think it makes sense to make it internal and provide something better in the public API.

**Comment by czurnieden** [comment]
> there is upcoming work by @czurnieden regarding a generalised prime sieve

Still lingering in limbo.
It needs a rebase now and probably some formal changes to reflect the changed API but is otherwise fully functional.

> @czurnieden I know you argued before that we will probably keep this function just as a quick early test. But I think it makes sense to make it internal and provide something better in the public API.

No problem.

**Comment by minad** [comment]
> Still lingering in limbo. It needs a rebase now and probably some formal changes to reflect the changed API but is otherwise fully functional.

Sure that's ok and there is no hurry. I just want to take a tiny step towards it and I am ticking of some things in #243.

**Comment by minad** [comment]
rebased

**Comment by sjaeckel** [comment]
can you please fix the conflicts

**Comment by minad** [comment]
done

**Pull request merged**
