### PR TITLE
addition of mp_expt (all input bigint)

### PR DESCRIPTION
**Pull request by czurnieden**
An exponentiation function like `mp_expt_d` but with all input having the type `mp_int`.
Needed for low-MP.

The test for this function will time-out because it uses the original `mp_n_root_ex` function. Works well with the version in #189

### CODE REVIEW

**Comment by czurnieden** [comment]
Mmh&hellip;for some reason the function to add the leading and trailing comments to the new files in dep.pl doesn't work anymore? The backslashes for the dollar signs in the end-comment gets printed! Works without the backslashes. WTF?
And who did it? Oh, me. \*grrr\*
OK, will check it out.

**Comment by czurnieden** [comment]
Ah, that was mean! ;-)
Oversaw the [single quotes](https://www.perlmonks.org/?node_id=736989)

**Comment by minad** [comment]
@czurnieden Would it make sense to instead extend mp_expt_d_ex/mp_expt_d to accept larger exponents than mp_digit (maybe call them mp_expt_int_ex/mp_expt_int)? Then we could avoid this function.

**Comment by czurnieden** [comment]
> Would it make sense to instead extend mp_expt_d_ex/mp_expt_d to accept larger exponents than mp_digit (maybe call them mp_expt_int_ex/mp_expt_int)? 

I found no easy way to do so.
And as most people use the "normal" `expt_d` function, the bigint one is more for the low-mp users, especially the 8-bitters,  I made it a separate function instead that you can exclude from the build if you don't need it.
But, as hinted on above: if you find a neat way to merge those two, I would be all in for it.

**Comment by minad** [comment]
@czurnieden This one can be closed right? Instead we want mp_expt_int or sth similar.

**Pull request closed without merging**
