### PR TITLE
Re-license

### LINKED ISSUE #126: please add a BSD2 or MIT style  option for the license
I've been talking with GHC dev collaborators, and we'd like to consider libtommath as a non GPL'd option for ghc's big nat/integer facilities.

to do so, we'd love for you to augment your dual licensing with perhaps a MIT or BSD2 license. 

I realize that wttfyw (wtfpl )/ public domain  dedication *should* be enough, but some people are sticklers, and apparently in some countries the notion of public domain doesn't exist. :(  

i'm happy to help / try  email all the listed contributors if thats something that could be deemed helpful.

Either way this is a fine library and we want to help put it in the hands of more people :)

### PR DESCRIPTION
**Pull request by sjaeckel**
In order to finally be able to close #126 and #76 we had some internal discussions and came to the conclusion that the proposed license is the only one that is acceptable to all maintainers of the libtom projects.

I will (most likely) write a longer news post about reasoning etc. but this should hopefully bring all those endless discussions regarding the PD/WTFPL to an end.

### CODE REVIEW

**Comment by karel-m** [comment]
We should perhaps also replace the initial comment in all source files like this:
```c
/* LibTomMath is free and unencumbered software released into
 * the public domain.
 *
 * For full licence see LICENCE file in the root of LibTomMath 
 * distribution or <http://unlicense.org/>.
 */
```
I can commit these changes to `relicense` branch once the wording is fixed.

**Comment by karel-m** [comment]
It would be also nice to create CONTRIBUTING file in the root saying something like this (original taken from https://unlicense.org/WAIVER):

```
By contributing to LibTomMath project you agree with the following
copyright waiver:

I dedicate any and all copyright interest in this software to the
public domain. I make this dedication for the benefit of the public at
large and to the detriment of my heirs and successors. I intend this
dedication to be an overt act of relinquishment in perpetuity of all
present and future rights to this software under copyright law.

To the best of my knowledge and belief, my contributions are either
originally authored by me or are derived from prior works which I have
verified are also in the public domain and are not subject to claims
of copyright by other parties.

To the best of my knowledge and belief, no individual, business,
organization, government, or other entity has any copyright interest
in my contributions, and I affirm that I will not make contributions
that are otherwise encumbered.
```
And in the pull request template we can add a checkbox like this:

* [ ] I agree with LibtomMath contribution rules described in [CONTRIBUTING](https://github.com/libtom/libtommath/blob/develop/CONTRIBUTING)

**Comment by sjaeckel** [comment]
> We should perhaps also replace the initial comment in all source files like this:

not sure though if it wouldn't be sufficient to replace the last sentence 'The library is free for all purposes without any express guarantee it works.' by something like 'SPDX-License-Identifier: Unlicense'? ...I somehow like the initial comment as it is... but we could also drop it entirely...

> create CONTRIBUTING file

I also thought about it already...

> And in the pull request template we can add a checkbox like this:

oh yeah, I see already how well this will work if I look at the current checkboxes we provide \[/sarcasm\] ;-)

**Comment by buggywhip** [comment]
> On Dec 26, 2018, at 6:34 AM, Steffen Jaeckel <notifications@github.com> wrote:
> 
> not sure though if it wouldn't be sufficient to replace the last sentence 'The library is free for all purposes without any express guarantee it works.' by something like 'SPDX-License-Identifier: Unlicense'? ...I somehow like the initial comment as it is... but we could also drop it entirely...

A brief reminder is not a bad idea so I’d keep as is but drop the word “express”.  ...less is more.  

If you don’t you may need to add “or implied“ and then you are rewriting the license.  Nah. 

You might consider adding “For details see the LICENSE file.”


Sent fm iTouch

**Pull request merged**
