### PR TITLE
Cleanup and update of manual

### PR DESCRIPTION
**Pull request by czurnieden**
Regarding e.g.: #406 

It is a lot, please check if nothing was forgotten, is wrong, or can go, thank you!

### CODE REVIEW

**Comment by minad** [comment]
@sjaeckel This is also good to merge I think!

**Comment by sjaeckel** [comment]
now that the first build job also checks the doc it will stay up-to-date I hope ;-)

**Comment by sjaeckel** [comment]
AFAIU this version of the docs also applies to 1.2.0, right!? so it'll make sense to use these changes (minus `MP_8BIT` removal) there as well!?

**Comment by czurnieden** [comment]
> AFAIU this version of the docs also applies to 1.2.0, right!?

I finished it before the last commit feast, so I think it should, yes.

> so it'll make sense to use these changes (minus MP_8BIT removal) there as well!?

An official release should have an up-to-date documentation, yes.
(Is the 8-bit support even mentioned in the docs?)

**Pull request merged**
