### PR TITLE
repair of #333

### PR DESCRIPTION
**Pull request by czurnieden**
As the title suggests: in re #333

### CODE REVIEW

**Comment by sjaeckel** [comment]
wouldn't "always doing the scan upwards" have the same result but with less code?

**Comment by czurnieden** [comment]
> wouldn't "always doing the scan upwards" have the same result but with less code?

Probably?

But I try to change as little as possible in bugfixes.
Refactoring is a terrain better fitted for e,.g.: @minad ;-)

**Comment by minad** [comment]
Add regression test?

**Comment by czurnieden** [comment]
> Add regression test?

Oh, that's very nice of you!

**Comment by minad** [comment]
😁

**Comment by czurnieden** [comment]
Found another problem with input zero while writing the test.
Or the test is buggy ;-)

**Comment by czurnieden** [comment]
Argh, forgot to mention that the bug seems to be fixed now (#333 and the problem with input smaller than 2).
Squash and merge?

@sjaeckel : 
> wouldn't "always doing the scan upwards" have the same result but with less code?

Makes more sense now, faced with the second problem (input smaller than 2) so: refactor or use this bugfix (for now)?

**Comment by sjaeckel** [comment]
> Pushed it onto this branch for you to look at.

cool!

> But doesn't look that much cleaner, tbh.

you really think so? I think it's much cleaner that way and also it's easier to understand, would you mind doing a rebase and opening a PR?

**Pull request merged**
