### PR TITLE
Simplify scripts

### PR DESCRIPTION
**Pull request by minad**
* remove updatemakes
* ~start to remove dep.pl (should be part of helper.pl)~
* dep.pl is now part of helper.pl

### CODE REVIEW

**Comment by minad** [comment]
@sjaeckel I hope we can avoid adding new scripts and put all the generation tasks inside helper.pl. dep.pl is a legacy script which is now also part of helper.pl

**Comment by sjaeckel** [comment]
there's one thing that breaks... no `./updatemakes.sh -c` anymore ;)

**Comment by minad** [comment]
> there's one thing that breaks... no ./updatemakes.sh -c anymore ;)

Yes, that's intentional. I think it is better if the scripts don't mess with git and I never used this. Agree?

**Comment by minad** [comment]
Haha, the data agrees with me.

~~~
$ git log --oneline | grep 'Update makefiles$' | wc
0 0 0
~~~

**Pull request merged**
