### PR TITLE
Fix additional warnings

### PR DESCRIPTION
**Pull request by minad**
Hi,

I am using libtommath in a project with more strict compilation warnings. Would it be possible to merge these upstream? What about -Wsystem-headers, why is this warning active? 

Furthermore I use multiple additional functions, which could be upstreamed. These functions address the issues #3 and #32 (see below). Would you be interested in those?

Daniel

~~~ c
int mp_set_double(mp_int* a, double x) {
    if (!__builtin_isfinite(x)) {
        mp_zero(a);
        return MP_OKAY;
    }
    const uint64_t bits = (uint64_t)x;
    const int exp = ((int)(bits >> 52) & 0x7FF) - 1023 - 52;
    const uint64_t frac = (bits & ((1ULL << 52) - 1)) | (1ULL << 52);

    int res = mp_set_long_long(a, frac);
    if (res != MP_OKAY)
        return res;
    res = exp < 0 ? mp_div_2d(a, -exp, a, 0) : mp_mul_2d(a, exp, a);
    if ((bits >> 63) && !mp_iszero(a))
        SIGN(a) = MP_NEG;
    return MP_OKAY;
}

// TODO replace with faster version, which directly manipulates the double bits.
double mp_get_double(const mp_int* a) {
    double d = 0;
    for (int i = USED(a); i --> 0;)
        d = d * pow(2, DIGIT_BIT) + (double)DIGIT(a, i);
    return mp_isneg(a) ? -d : d;
}

// See https://github.com/libtom/libtommath/issues/32 by @hikari-no-yume
typedef enum { mp_xor, mp_or, mp_and } mp_op;
int mp_bitwise(mp_op op, const mp_int *a, const mp_int *b, mp_int *c) {
    int res = MP_OKAY;
    bool as = mp_isneg(a), bs = mp_isneg(b), s = false;
    mp_int *max = 0, _max, acopy, bcopy;

    if (as || bs) {
        int bits = max(mp_count_bits(a), mp_count_bits(b));
        res = mp_init_set_int(&_max, 1);
        if (res != MP_OKAY)
            goto end;
        max = &_max;
        res = mp_mul_2d(max, bits + 1, max);
        if (res != MP_OKAY)
            goto end;
        if (as) {
            res = mp_init(&acopy);
            if (res != MP_OKAY)
                goto end;
            res = mp_add(max, a, &acopy);
            if (res != MP_OKAY) {
                mp_clear(&acopy);
                goto end;
            }
            a = &acopy;
        }
        if (bs) {
            res = mp_init(&bcopy);
            if (res != MP_OKAY)
                goto end;
            res = mp_add(max, b, &bcopy);
            if (res != MP_OKAY) {
                mp_clear(&bcopy);
                goto end;
            }
            b = &bcopy;
        }
    }

    switch (op) {
    case mp_or:  res = mp_or(a, b, c);  s = as | bs; break;
    case mp_xor: res = mp_xor(a, b, c); s = as ^ bs; break;
    case mp_and: res = mp_and(a, b, c); s = as & bs; break;
    }

    if (s && res == MP_OKAY)
        res = mp_sub(c, max, c);

end:
    if (a == &acopy) mp_clear(&acopy);
    if (b == &bcopy) mp_clear(&bcopy);
    if (max == &_max) mp_clear(max);
    return res;
}

int mp_not(const mp_int *a, mp_int *b) {
    int res = mp_neg(a, b);
    return res == MP_OKAY ? mp_sub_d(b, 1, b) : res;
}

int mp_shr(const mp_int *a, int b, mp_int *c) {
    if (!mp_isneg(a))
        return mp_div_2d(a, b, c, 0);
    int res = mp_add_d(a, 1, c);
    if (res != MP_OKAY)
        return res;
    res = mp_div_2d(c, b, c, 0);
    return res == MP_OKAY ? mp_sub_d(c, 1, c) : res;
}
~~~

### CODE REVIEW

**Comment by minad** [comment]
I've just seen there are a lot more conversion warnings in the different test suites. If you are interested in the stricter warnings I can repair those too.

**Comment by sjaeckel** [comment]
Sorry for the long delay, I like the idea of this PR!

As the remaining warnings are only in `demo.c` I think we can merge it after they're fixed!

Regarding the double functions: sure! Feel free to open another PR :)

**Comment by sjaeckel** [comment]
> @sjaeckel Sure, I can create PRs for those functions. However right now I have no understanding of the test suite. Could you point me to the files where I can add tests?

there's no real test suite...

you can add cases to [demo.c](https://github.com/libtom/libtommath/blob/develop/demo/demo.c) ... I'd say around line 263 before `mp_get_int()` 

... which reminds me that we should really clean this up and improve on it ;) but at least this spaghetti monster brings us ~75% coverage ...

**Comment by minad** [comment]
this PR is outdated

**Pull request closed without merging**
