### PR TITLE
Change type for result of mp_count_bits to size_t

### PR DESCRIPTION
**Pull request by czurnieden**
Change `int mp_count_bits(mp_int *a)` to `mp_err mp_count_bits(mp_int *a, size_t *size)`.

It is only a start (`demo/*c` not even touched for now) because changing `mp_count_bits` leads to a couple of changes in other functions. See comments in sources.

### CODE REVIEW

**Comment by minad** [comment]
Can you please delay working on this until we have the open PRs merged? You also have multiple open ones with unclear status.

Let's please discuss first on how we proceed with such a large scale refactoring since it touches many functions and will invalidate all PRs.

**Comment by nijtmans** [comment]
Sorry, but I don't like this. If mp_count_bits() returns an error, it means a situation that mp_count_bits cannot handle because its result doesn't have enough bits to represent it. So, the correct solutions is to increase this number of bits, so change size_t to unsigned long or unsigned long long. This way, the callers of mp_count_bits don't have to handle the error-situation, they just have to be modified to handle enough bits for the count. Just my 2c....

**Comment by minad** [comment]
I have to think about this more. I would also like the type should be sufficient to represent the number of bits. But using uint64_t on 64 bit platforms is also a bit crazy. I would like to have it such that size_t is large enough for the bits, checked before malloc. Unfortunately this means that only 8kib numbers can be represented on 64k platforms which might not be good enough?

**Comment by minad** [comment]
We could also define our own bits_t type which is always large enough. size_t or uint32_t on 16 bit platforms.

**Comment by minad** [comment]
@czurnieden can we close this for now. More discussion is needed before doing anything.

**Comment by czurnieden** [comment]
> Can we close this for now? More discussion is needed before doing anything.

As a discussion is already starting we can discuss it here. Or do you want to do it more formally with an "Issue"? 

And to be honest, this PR was meant to start a discussion. Changing the type will be a great pain in the behind, that rabbithole is really deep and I have chosen this example because it nicely shows some of the complications we can expect if we replace all of the `int`s with a single native data type of variable size (here: `size_t`).

And yes, the check should be done at the (re)allocation stage(s). It is the right place for it and they already return errors so `mp_count_bits` can keep its comfortable API and just return the size.

And now back to rebasing because somebody really got to town this weekend with PR-merging! ;-)

**Comment by minad** [comment]
Let's do it in the issue #363 please. I think we are both well aware of the complications. There is also the issue with signed loop variables vs unsigned loop variables. Furthermore since many things interact here it will be hard to split the work (you also have many TODOs due to that).

But still it should be better to make a nice plan. Maybe we can identify a few things that can be done in a step by step basis.

**Pull request closed without merging**
