### PR TITLE
add COMPILE_LTO to test link time optimization

### PR DESCRIPTION
**Pull request by minad**
the library performs best with lto since many small functions
can be inlined across objects.

### CODE REVIEW

**Comment by minad** [comment]
How is llvm-ar-7 llvm-ranlib-7 etc called on ubuntu?

**Comment by sjaeckel** [comment]
```
$ llvm-ranlib-
llvm-ranlib-3.5  llvm-ranlib-5.0  llvm-ranlib-7 
$ llvm-ar-
llvm-ar-3.5  llvm-ar-5.0  llvm-ar-7
```

**Comment by minad** [comment]
For some reason it is not there. Do we need an additional package? llvm-7-tools?

**Comment by sjaeckel** [comment]
```
$ dpkg -S llvm-ranlib-7
llvm-7: /usr/bin/llvm-ranlib-7
```
looks like `llvm-7` isn't installed

**Comment by sjaeckel** [comment]
... :-\

**Comment by sjaeckel** [comment]
I'm not sure if that shouldn't be reported to travis... looks to me like an incomplete installation and nobody noticed until now

**Pull request merged**
