### PR TITLE
Fix msvc build warnings

### PR DESCRIPTION
**Pull request by nijtmans**
Proposed solution for MSVC warning. It appears an additional pair of braces helps.

### CODE REVIEW

**Comment by nijtmans** [comment]
Apparently, this doesn't work :-(

**Comment by minad** [comment]
Uh no. But adding a pragma to tommath_private.h should do it. I guess you don't include the private header anywhere in tcl? This would restrict the disabled warning to the relevant files only.

**Comment by nijtmans** [comment]
I would welcome such a pragma in tommath_private.h. Yes, Tcl includes this, so that - indeed - should work too.

**Comment by sjaeckel** [comment]
> If you have time to prepare a PR I would appreciate it. I guess @sjaeckel could still add it to 1.2.

@nijtmans feel free to open a PR based on release/1.2.0 or if "you're sure it works"^TM simply commit it to the release/1.2.0 branch ;-)

**Pull request closed without merging**
