### PR TITLE
add feature detection macro MP_HAS (2)

### PR DESCRIPTION
**Pull request by minad**
See #214. I wanted to try again if I can make this work without using variadic macros, this time only relying on C89.

@karel-m Could you please try again your compiler suite?

@sjaeckel @czurnieden This PR is simpler and better than the one before. Hopefully it also works on older compilers. This helps to clean up control flow. Another advantage is that the compiler will check all branches. Dead code elimination will make sure that the dead branches are not compiled.

### CODE REVIEW

**Comment by minad** [comment]
@sjaeckel What do we have to check here to make sure that this change does not break any things? I don't think it does, but what do you guys need to be convinced :wink: 

If you are worried about dead code elim, try this with `gcc -o dead dead.c`

~~~ c
/* dead.c */
#include <stdio.h>

void does_not_exist(void);

int main(void) {
        if (sizeof("") == 1) {
                puts("We're ok");
        }
        if (sizeof("X") == 1) {
                does_not_exist();
        }
        return 0;
}
~~~

**Comment by minad** [comment]
In contrast to the solution in #214, this works on MSVC 2015 and 2017 as I just tested using appveyor.

**Comment by sjaeckel** [comment]
@karel-m can you please have a look if this works for your cases as well?

**Comment by minad** [comment]
> Nitpicking: #262  relies on the compiler to optimize the "dead code" away. 

Yes. We discussed that before, this is common practice. Many projects rely on that kind of dead code elimination. Please find me a compiler which is incapable of optimizing `if (2 == 1) { ... }` away. Note that the sizeof is guaranteed to be evaluated at compile time.

The warning is not an important issue I think. More intelligent compilers don't complain (gcc and clang for example). I think for us it is important that our CI builds build cleanly with the very restrictive settings we are using. Btw our settings are much more restrictive than what other projects use and that's pretty good.

**Comment by minad** [comment]
I looked around a bit. And I tried to convince gcc to still include the trivially dead code - I did not succeed (I tried for example -fno-dce). Look at the answer to https://stackoverflow.com/questions/39832958/gcc-o0-still-optimizes-out-unused-code-is-there-a-compile-flag-to-change-tha/39833806

It says for example:

> GCC doesn't "optimize out" anything here. It just doesn't generate useless code. It seems to a very common illusion that there's some pure form of code that the compiler should generate and any changes to that are an "optimization". There is no such thing.

**Comment by karel-m** [comment]
Microsoft Visual Studio 2017 works with some warnings (IMO unrelated to this PR):

```
1>------ Build started: Project: tommath, Configuration: Debug x64 ------
[...]
1>bn_s_mp_rand_platform.c
1>bn_s_mp_rand_platform.c(141): warning C4003: not enough actual parameters for macro 'MP__STRINGIZE'
[...]
1>bn_s_mp_mul_high_digs.c
1>bn_s_mp_mul_high_digs.c(19): warning C4003: not enough actual parameters for macro 'MP__STRINGIZE'
[...]
1>bn_s_mp_exptmod_fast.c
1>bn_s_mp_exptmod_fast.c(74): warning C4003: not enough actual parameters for macro 'MP__STRINGIZE'
1>bn_s_mp_exptmod_fast.c(85): warning C4003: not enough actual parameters for macro 'MP__STRINGIZE'
1>bn_s_mp_exptmod_fast.c(89): warning C4003: not enough actual parameters for macro 'MP__STRINGIZE'
1>bn_s_mp_exptmod_fast.c(97): warning C4003: not enough actual parameters for macro 'MP__STRINGIZE'
1>bn_s_mp_exptmod_fast.c(105): warning C4003: not enough actual parameters for macro 'MP__STRINGIZE'
1>bn_s_mp_exptmod_fast.c(129): warning C4003: not enough actual parameters for macro 'MP__STRINGIZE'
[...]
1>bn_mp_sqr.c
1>bn_mp_sqr.c(10): warning C4003: not enough actual parameters for macro 'MP__STRINGIZE'
1>bn_mp_sqr.c(13): warning C4003: not enough actual parameters for macro 'MP__STRINGIZE'
1>bn_mp_sqr.c(16): warning C4003: not enough actual parameters for macro 'MP__STRINGIZE'
1>bn_mp_sqr.c(20): warning C4003: not enough actual parameters for macro 'MP__STRINGIZE'
[...]
1>bn_mp_set_double.c
1>mp_set_double implementation is only available on platforms with IEEE754 floating point format
[...]
1>bn_mp_reduce.c
1>bn_mp_reduce.c(29): warning C4003: not enough actual parameters for macro 'MP__STRINGIZE'
1>bn_mp_reduce.c(33): warning C4003: not enough actual parameters for macro 'MP__STRINGIZE'
[...]
1>bn_mp_rand.c
1>bn_mp_rand.c(9): warning C4028: formal parameter 1 different from declaration
[...]
1>bn_mp_mul.c
1>bn_mp_mul.c(15): warning C4003: not enough actual parameters for macro 'MP__STRINGIZE'
1>bn_mp_mul.c(28): warning C4003: not enough actual parameters for macro 'MP__STRINGIZE'
1>bn_mp_mul.c(31): warning C4003: not enough actual parameters for macro 'MP__STRINGIZE'
1>bn_mp_mul.c(34): warning C4003: not enough actual parameters for macro 'MP__STRINGIZE'
1>bn_mp_mul.c(44): warning C4003: not enough actual parameters for macro 'MP__STRINGIZE'
[...]
1>bn_mp_invmod.c
1>bn_mp_invmod.c(15): warning C4003: not enough actual parameters for macro 'MP__STRINGIZE'
1>bn_mp_invmod.c(19): warning C4003: not enough actual parameters for macro 'MP__STRINGIZE'
[...]
1>bn_mp_exptmod.c
1>bn_mp_exptmod.c(25): warning C4003: not enough actual parameters for macro 'MP__STRINGIZE'
1>bn_mp_exptmod.c(55): warning C4003: not enough actual parameters for macro 'MP__STRINGIZE'
1>bn_mp_exptmod.c(61): warning C4003: not enough actual parameters for macro 'MP__STRINGIZE'
1>bn_mp_exptmod.c(64): warning C4003: not enough actual parameters for macro 'MP__STRINGIZE'
1>bn_mp_exptmod.c(69): warning C4003: not enough actual parameters for macro 'MP__STRINGIZE'
1>bn_mp_exptmod.c(71): warning C4003: not enough actual parameters for macro 'MP__STRINGIZE'
[...]
1>bn_mp_div_d.c
1>bn_mp_div_d.c(61): warning C4003: not enough actual parameters for macro 'MP__STRINGIZE'
[...]
1>bn_conversion.c
1>bn_conversion.c(64): warning C4146: unary minus operator applied to unsigned type, result still unsigned
1>bn_conversion.c(68): warning C4146: unary minus operator applied to unsigned type, result still unsigned
1>bn_conversion.c(72): warning C4146: unary minus operator applied to unsigned type, result still unsigned
1>bn_conversion.c(76): warning C4146: unary minus operator applied to unsigned type, result still unsigned
[...]
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
```

gcc-8.3 + mingw-w64 works fine with just one warning (you have to explicitely turn on `-Wredundant-decls`):

```
gcc -I. -Wextra -Wall  -Wredundant-decls -c bn_s_mp_rand_platform.c -o bn_s_mp_rand_platform.o
bn_s_mp_rand_platform.c:132:8: warning: redundant redeclaration of 's_read_wincsp' [-Wredundant-decls]
 mp_err s_read_wincsp(void *p, size_t n);
        ^~~~~~~~~~~~~
bn_s_mp_rand_platform.c:34:15: note: previous definition of 's_read_wincsp' was here
 static mp_err s_read_wincsp(void *p, size_t n)
               ^~~~~~~~~~~~~
```

Pretty old gcc version 3.4.4 fails badly:

```
$ make CC=gcc
   * gcc bn_conversion.o
In file included from tommath_private.h:7,
                 from bn_conversion.c:1:
tommath.h:232: error: wrong number of arguments specified for `deprecated' attribute
tommath.h:313: error: wrong number of arguments specified for `deprecated' attribute
tommath.h:314: error: wrong number of arguments specified for `deprecated' attribute
tommath.h:315: error: wrong number of arguments specified for `deprecated' attribute
tommath.h:316: error: wrong number of arguments specified for `deprecated' attribute
tommath.h:317: error: wrong number of arguments specified for `deprecated' attribute
tommath.h:318: error: wrong number of arguments specified for `deprecated' attribute
tommath.h:319: error: wrong number of arguments specified for `deprecated' attribute
tommath.h:370: error: wrong number of arguments specified for `deprecated' attribute
tommath.h:390: error: wrong number of arguments specified for `deprecated' attribute
tommath.h:393: error: wrong number of arguments specified for `deprecated' attribute
tommath.h:397: error: wrong number of arguments specified for `deprecated' attribute
tommath.h:401: error: wrong number of arguments specified for `deprecated' attribute
tommath.h:408: error: wrong number of arguments specified for `deprecated' attribute
tommath.h:471: error: wrong number of arguments specified for `deprecated' attribute
tommath.h:507: error: wrong number of arguments specified for `deprecated' attribute
tommath.h:519: error: wrong number of arguments specified for `deprecated' attribute
tommath.h:586: error: wrong number of arguments specified for `deprecated' attribute
tommath.h:589: error: wrong number of arguments specified for `deprecated' attribute
tommath.h:664: error: wrong number of arguments specified for `deprecated' attribute
In file included from bn_conversion.c:1:
tommath_private.h:219: error: wrong number of arguments specified for `deprecated' attribute
tommath_private.h:221: error: wrong number of arguments specified for `deprecated' attribute
tommath_private.h:223: error: wrong number of arguments specified for `deprecated' attribute
tommath_private.h:226: error: wrong number of arguments specified for `deprecated' attribute
tommath_private.h:227: error: wrong number of arguments specified for `deprecated' attribute
tommath_private.h:228: error: wrong number of arguments specified for `deprecated' attribute
tommath_private.h:231: error: wrong number of arguments specified for `deprecated' attribute
tommath_private.h:232: error: wrong number of arguments specified for `deprecated' attribute
tommath_private.h:233: error: wrong number of arguments specified for `deprecated' attribute
tommath_private.h:234: error: wrong number of arguments specified for `deprecated' attribute
tommath_private.h:235: error: wrong number of arguments specified for `deprecated' attribute
tommath_private.h:236: error: wrong number of arguments specified for `deprecated' attribute
tommath_private.h:237: error: wrong number of arguments specified for `deprecated' attribute
make: *** [bn_conversion.o] Error 1
```

**Comment by minad** [comment]
Gcc 3.4 fail also seems unrelated to this PR.

**Comment by minad** [comment]
Msvc warnings are related to this PR but they are pretty much harmless.

**Comment by minad** [comment]
@karel-m does it work with the other compilers?

**Comment by karel-m** [comment]
I do not have other exotic compilers at my hand at the moment.

**Comment by minad** [comment]
@sjaeckel Ok, then I would say we are good here. I pushed a fix for the deprecation errors in gcc 3.

**Comment by czurnieden** [comment]
> mp_set_double implementation is only available on platforms with IEEE754 floating point format

I thought we had that already sorted out for MSVC?

**Comment by minad** [comment]
> mp_set_double implementation is only available on platforms with IEEE754 floating point format
> I thought we had that already sorted out for MSVC?

No I don't think so. There is also #159. But let's discuss this in a separate issue/PR please.

**Comment by karel-m** [comment]
Literally an epic fail on IBM AIX 7.1 + IBM XL C/C++ compiler:

```
> make CC=xlc V=1 -f makefile.unix
        xlc -I. -O2 -c bn_conversion.c -o bn_conversion.o
"tommath.h", line 232.49: 1506-166 (S) Definition of function mp_rand_source requires parentheses.
"tommath.h", line 232.65: 1506-276 (S) Syntax error: possible missing '{'?
"/usr/include/stdlib.h", line 113.3: 1506-273 (E) Missing type in declaration of div_t.
"tommath_private.h", line 219.15: 1506-485 (S) Parameter declaration list is incompatible with declarator for s_mp_invmod_fast.
"tommath_private.h", line 220.14: 1506-276 (S) Syntax error: possible missing '{'?
"bn_conversion.c", line 56.1: 1506-045 (S) Undeclared identifier b.
"bn_conversion.c", line 56.1: 1506-045 (S) Undeclared identifier a.
"bn_conversion.c", line 80.12: 1506-343 (S) Redeclaration of mp_get_mag32 differs from previous declaration on line 72 of "bn_conversion.c".
"bn_conversion.c", line 80.12: 1506-050 (I) Return type "unsigned int" in redeclaration is not compatible with the previous return type "int".
"bn_conversion.c", line 84.12: 1506-343 (S) Redeclaration of mp_get_mag64 differs from previous declaration on line 76 of "bn_conversion.c".
"bn_conversion.c", line 84.12: 1506-050 (I) Return type "unsigned long long" in redeclaration is not compatible with the previous return type "int".
make: 1254-004 The error code from the last command is 1.

Stop.
```

operating system:
```
> uname -a
AIX l3ferp001_pub 1 7 00F7F3FE4C00

> oslevel -s
7100-05-03-1846

> prtconf
Processor Type: PowerPC_POWER7
...
```

compiler:
```
> xlc -qversion
IBM XL C/C++ for AIX, V11.1 (5724-X13)
Version: 11.01.0000.0003
```

**Comment by minad** [comment]
@karel-m the fail on aix has nothing to do with this patch. Can you provide a fix?

**Comment by karel-m** [comment]
> the fail on aix has nothing to do with this patch

It might be true; however, the libtommath-1.1.0 builds fine on the same system with just one expected warning related to "IEEE754 floating point format". And I am sad about the way how we nowadays treat non-gcc compilers we used to support.

> Can you provide a fix?

It is very unlikely in the next 2 months.

**Comment by minad** [comment]
> It might be true; however, the libtommath-1.1.0 builds fine on the same system with just one expected warning related to "IEEE754 floating point format". And I am sad about the way how we nowadays treat non-gcc compilers we used to support.

We support old gcc, clang, msvc and even check those with ci. The situation improved for those compilers. I think we would all be happy to support other compilers, but it is quite hard since we cannot test those in ci and even worse, we might not even have access to those. I think supporting other compilers is only possible if people using them are willing to contribute some time. Furthermore support for other compilers has not been dropped since no release has been made. Before a new release is made, all the issues can be fixed if that is desired.

**Comment by sjaeckel** [comment]
> and even worse, we might not even have access to those

well at least IBM XL is available as a free of charge community edition for ppc64le [1]

[1] https://www.ibm.com/developerworks/community/blogs/572f1638-121d-4788-8bbb-c4529577ba7d/entry/Evaluating_XL_C_C_for_Linux_V13_1_4_with_the_no_charge_unlimited_license_for_production_use_Community_Edition?lang=en

**Comment by minad** [comment]
> well at least IBM XL is available as a free of charge community edition for ppc64le [1]

Good to know. I suggest we fix the xlc issues before release.

**Comment by karel-m** [comment]
This seems to fix IBM xlc troubles:
```diff
 #if defined(__GNUC__) && __GNUC__ >= 4
 #  define MP_DEPRECATED(x) __attribute__((deprecated("replaced by " #x)))
 #  define PRIVATE_MP_DEPRECATED_PRAGMA(s) _Pragma(#s)
 #  define MP_DEPRECATED_PRAGMA(s) PRIVATE_MP_DEPRECATED_PRAGMA(GCC warning s)
 #elif defined(_MSC_VER) && _MSC_VER >= 1500
 #  define MP_DEPRECATED(x) __declspec(deprecated("replaced by " #x))
 #  define MP_DEPRECATED_PRAGMA(s) __pragma(message(s))
 #else
-#  define MP_DEPRECATED
+#  define MP_DEPRECATED(s)
 #  define MP_DEPRECATED_PRAGMA(s)
 #endif
```

Which is exactly what I would call the slightly growing lack of attention to unusual compilers.

**Comment by minad** [comment]
> Which is exactly what I would call the slightly growing lack of attention to unusual compilers.

This is what I call "a typo", nothing to complain about. Thank you for the fix.

**Comment by karel-m** [comment]
> This is what I call "a typo", nothing to complain about.

Obviously. What I wanted to say is that nobody tried any compiler that hits `#else` branch.

**Comment by minad** [comment]
@sjaeckel Ready?

**Comment by minad** [comment]
@sjaeckel What is your opinion about this PR now?

**Comment by sjaeckel** [comment]
> Obviously. What I wanted to say is that nobody tried any compiler that hits `#else` branch.

I'm not sure where the culprit has to be searched there... in the compiler providers who mostly try to mimic gcc or the ones who don't mimic gcc not being available easily...

Which compilers did we test this now with?

* gcc down to 3.4
* clang multiple versions
* MSVC multiple versions
* IBM xlc 11.1

Something missing? If this works with all those compilers I think it's safe to merge.

**Comment by minad** [comment]
@sjaeckel yes, the compilers you listed are the ones we tested so far.

**Comment by minad** [comment]
@sjaeckel I rebased this PR again on develop. CI all green.

**Comment by minad** [comment]
Ping @sjaeckel. Could you merge this PR or are there things to do?

**Comment by czurnieden** [comment]
> @czurnieden anything to add?

To `mp_mul`?
Yes, but not today, that'll need a bit longer ;-)

Otherwise: no problems, can tick it off, too.

**Comment by minad** [comment]
@czurnieden Thanks!

@sjaeckel 
> I still don't really like those complex if-elseif statements/chain e.g. in mp_mul() but I could live with it...

Yes, it might be possible to improve this. In order to not introduce any unwanted changes, I took the most direct translation from the intermingled #if and if branches.

**Comment by minad** [comment]
@sjaeckel ping?

**Pull request merged**
