### PR TITLE
Addition of a man-page

### PR DESCRIPTION
**Pull request by czurnieden**
A Troff formatted man-page.

### CODE REVIEW

**Comment by czurnieden** [comment]
It is currently just an alphabetical list of LibTomMath's functions with the obligatory man-page boilerplates.

**Comment by sjaeckel** [comment]
How did you generate this? (Please don't say by hand 😂)

**Comment by czurnieden** [comment]
> How did you generate this? (Please don't say by hand )

How can I answer that question if you forbid me to tell you? ;-)

But serious: grep'd the functions, formatted them with a bit of sed and tr and c&p'ed a lot of text from bn.tex.
Tables were a bit fiddly, but they seem to work now.

**Comment by czurnieden** [comment]
Seems as if I am innocent this time:

```
 E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/b/babeltrace/libbabeltrace1_1.5.8-1build1_amd64.deb  503  Service Unavailable [IP: 40.119.46.219 80]
```

**Comment by czurnieden** [comment]
Digged through my shell history:

```sh
grep -E "^mp_err" doc/bn.tex | sed -e 's/ /\\ /g;s/^/.LP /' >> ~/DIV_C_FILES/ltm_functions
grep -E "^void" doc/bn.tex | sed -e 's/ /\\ /g;s/^/.LP /' >> ~/DIV_C_FILES/ltm_functions
grep -E "^int" doc/bn.tex | sed -e 's/ /\\ /g;s/^/.LP /' >> ~/DIV_C_FILES/ltm_functions
grep -E "^uint" doc/bn.tex | sed -e 's/ /\\ /g;s/^/.LP /' >> ~/DIV_C_FILES/ltm_functions
grep -E "^long" doc/bn.tex | sed -e 's/ /\\ /g;s/^/.LP /' >> ~/DIV_C_FILES/ltm_functions
grep -E "^bool" doc/bn.tex | sed -e 's/ /\\ /g;s/^/.LP /' >> ~/DIV_C_FILES/ltm_functions
grep -E "^size_t" doc/bn.tex | sed -e 's/ /\\ /g;s/^/.LP /' >> ~/DIV_C_FILES/ltm_functions
grep -E "define mp" doc/bn.tex | sed -e 's/ /\\ /g;s/^/.LP /' >> ~/DIV_C_FILES/ltm_functions
   ...
sort -u  ~/DIV_C_FILES/ltm_functions | > ~/DIV_C_FILES/ltm_functions_uniq
   ...
sort -k 3 ~/DIV_C_FILES/ltm_functions.troff  > ~/DIV_C_FILES/ltm_functions.troff_bis
mv -v ~/DIV_C_FILES/ltm_functions.troff_bis ~/DIV_C_FILES/ltm_functions.troff
```

The rest was done in the editor, so no "automagic" latex2troff here, sorry.

There is `latex2man` which I couldn't get working the way I wanted it to work but I did not spend a lot of time with it, so it might be my inability that was hindering `latex2man` to do its job.

**Comment by czurnieden** [comment]
> Can you please cross check what I added?

You added a check in `helper.pl` so it should be complete now.
I hope.

> Should we maybe also install the manpages from the regular makefiles?

Yes. We have it, we <del>brag about</del>use it.

What about the two random examples at the end? We have a couple in `etc` which&hellip;don't compile anymore. (path to `tommath*h` is wrong). Guh&hellip:reat. The implementation of the Maurer(?) algorithm in `pprime.c` has not been written for `MP_64BIT` it would take a couple of days as it is now. The link to the paper at `gmail.com` is broken (gets timeouts). And more.

Nah, not today, the odd problems with the timing over at #499 are enough for now.

**Comment by sjaeckel** [comment]
> What about the two random examples at the end? We have a couple in `etc` which…don't compile anymore. (path to `tommath*h` is wrong). Guh&hellip:reat. The implementation of the Maurer(?) algorithm in `pprime.c` has not been written for `MP_64BIT` it would take a couple of days as it is now. The link to the paper at `gmail.com` is broken (gets timeouts). And more.

I've fixed them (at least to compile w/o warnings), will push it after I've merged this PR.

**Comment by czurnieden** [comment]
> I've fixed them (at least to compile w/o warnings), will push it after I've merged this PR.

Oh, you are way too fast!
Or am I too slow? ;-)

Couldn't get even a start point with the radix conversion problem, so I grabbed the low hanging fruits first and repaired the files in `etc` in #561. But I repaired the Maurer algorithm in `pprime.c`, too. Replaced the giant small-prime database with a call to `mp_prime_next_prime` because `mp_prime_is_prime` is deterministic up to 64 bits (and more). and adapted the rest.

Sorry.

**Pull request merged**
