### PR TITLE
Follow-up of #489

### PR DESCRIPTION
**Pull request by sjaeckel**
This is a follow-up of #489 

It adds "automation" of the modifications to `tommath.def` and a travis job to check for this.

Additionally the proposed split-up of `mp_rand.c` is done and the modifications to `s_mp_rand_platform.c` are reverted.

### CODE REVIEW

**Comment by madebr** [comment]
FYI, this are the results of building libtommath on linux gcc, linux clang, macos and windows msvc: https://github.com/conan-io/conan-center-index/pull/2904#issuecomment-691671889
Don't mind the .la errors, I forgot to remove these.

**Review by czurnieden — APPROVED** [review]
I can't tell a lot about the Windows related changes, but the rest I like!

**Comment by madebr** [comment]
With the following changes, this pr allows building the tests linked to the dll.
```patch
--- a/appveyor.yml
+++ b/appveyor.yml
@@ -19,3 +19,4 @@ build_script:
         nmake -f makefile.msvc all
 test_script:
 - cmd: test.exe
+- cmd: test_dll.exe
--- a/makefile.msvc
+++ b/makefile.msvc
@@ -71,10 +71,15 @@ $(LIBMAIN_D) $(LIBMAIN_I): $(OBJECTS) tommath.def

 #Build test suite
 test.exe: $(LIBMAIN_S) demo/shared.obj demo/test.obj
-       cl $(LTM_CFLAGS) $(TOBJECTS) $(LIBMAIN_S) $(LTM_LDFLAGS) demo/shared.c demo/test.c /Fe$@
+       link $(TOBJECTS) $(LTM_LDFLAGS) $? /out:$@
        @echo NOTICE: start the tests by launching test.exe

-all: $(LIBMAIN_S) test.exe $(LIBMAIN_D)
+#Build test suite for dll
+test_dll.exe: $(LIBMAIN_I) demo/shared.obj demo/test.obj
+       link $(TOBJECTS) $(LTM_LDFLAGS) $? /out:$@
+       @echo NOTICE: start the tests by launching test_dll.exe
+
+all: $(LIBMAIN_S) test.exe $(LIBMAIN_D) test_dll.exe

 tune: $(LIBMAIN_S)
        $(MAKE) -C etc tune
```

**Comment by madebr** [comment]
The tests was failing in `test_mp_fread_fwrite`.
It looks like we need to override the default runtime when building dll's.
By default static runtime is used, but that does not work because the `mp_f*` api calls pass `FILE*` handles.
So use the shared `MD` runtime by default instead.
People can override the default by setting it in `CFLAGS`.

**Comment by madebr** [comment]
FYI, defining `LTM_TEST_DYNAMIC` is not absolutely required for msvc if you add `/O1` (or higher) to `CFLAGS` and add `/OPT:REF,ICF` to `LDFLAGS` (when builiding in debug mode).

**Review by czurnieden — APPROVED** [review]
Ubuntu's Bionic Beaver is version 18.04, you might change the comment above the distribution settings in `.travis.yml` otherwise: looks good for me!

**Pull request merged**
