### PR TITLE
Get rid of BN prefix

### PR DESCRIPTION
**Pull request by minad**
Another trivial one :grin:

In the beginning it seemed there were three different prefixes, MP, BN and LTM. Fortunately it seems we now settled on mp and s_mp. This renames all the things to comply with that.
Furthermore I find the current `bn_s_mp_` prefix a bit hard on the eye.

This is done similarly to #172 via a move script.

Not to be merged now, don't worry about all your open PRs!

### CODE REVIEW

**Comment by minad** [comment]
@sjaeckel Any reason to delay this PR for 2.0 (in general, what are you plans about a new release, removing deprecations etc)? This PR shouldn't have any user facing implications (no abi/api changes).

**Comment by sjaeckel** [comment]
> @sjaeckel Any reason to delay this PR for 2.0 (in general, what are you plans about a new release, removing deprecations etc)? This PR shouldn't have any user facing implications (no abi/api changes).

it changes the user facing defines in `tommath_class.h` that are used to trim the library, so I'd prefer to push this to 2.0

**Comment by minad** [comment]
tommath_class.h is not included in tommath.h anymore.

**Comment by sjaeckel** [comment]
> tommath_class.h is not included in tommath.h anymore.

that's true, but I still count this way of tweaking/configuring ltm as a feature that I don't want to break.

**Comment by minad** [comment]
@sjaeckel could you please merge this soon since otherwise we have to chaotically rebase everything very often. @czurnieden is already starting with new stuff.

Also #387, #388, #390 are ready for merge.

**Comment by sjaeckel** [comment]
I wanted to merge yesterday already but had to leave, sorry

**Pull request merged**
