### PR TITLE
additional functions mp_incr and mp_decr

### PR DESCRIPTION
**Pull request by czurnieden**
First batch.
The functions are interdependent, they call each other in case of negative input.

### CODE REVIEW

**Comment by minad** [comment]
Looks good except for the whitespace changes.

**Comment by czurnieden** [comment]
> Looks good except for the whitespace changes.

But @sjaeckel was very nice and helped me to install a hook to&hellip;oh, that was only for that branch not for all. My bad, sorry.

I'm currently building the PR for `mp_ilogb` which won't need long (hopefully ;-) ) and clean up when that is done.

**Comment by sjaeckel** [comment]
which whitespace changes?

**Comment by sjaeckel** [comment]
> What is the reason for that restriction?

Tests should only use the public API. For your case there's still `mp_iszero()`... but I can also live with `mp_cmd_d()`

**Comment by sjaeckel** [comment]
> which whitespace changes?

@minad \*ping\*

**Comment by minad** [comment]
@sjaeckel I was on mobile and I think I confused the two PRs by @czurnieden. See here https://github.com/libtom/libtommath/pull/191/files#diff-aa67c18ca27d74fae0446b5cd9376391L14.

**Pull request merged**
